name: Publish Package to npmjs
on:
  release:
    types: [created]
env:
  NODE_VERSION: '16.15.0'                # set this to the node version to use
  NODE_OPTIONS: "--max_old_space_size=5120"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: npm install and build raaghu-elements
      working-directory: raaghu-elements
      run: npm install
      
      - run: npm ci
      # - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
